AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: SAM Template for Youtube to Spotify Application
Resources:
  YoutubeToSpotifyFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: YoutubeToSpotify
      Description: Youtube to Spotify main function
      Role: arn:aws:iam::079866621733:role/YoutubeToSpotify
      CodeUri: s3://youtube-to-spotify/lambda-templates/youtube-to-spotify/cb2be61418ba72836cd7579b435e63e8
      Handler: main.handler
      Runtime: python3.7
      Timeout: 900
      MemorySize: 256
      Environment:
        Variables:
          ENV: production
      Layers:
      - Ref: YoutubeToSpotifyHelperLayer
  YoutubeToSpotifyHelperLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: YoutubeToSpotifyHelperLayer
      Description: Helper layer for Youtube to Spotify
      ContentUri: s3://youtube-to-spotify/lambda-templates/youtube-to-spotify/3e480daa0e8ee61327396e7a339d70b2
      CompatibleRuntimes:
      - python3.7
      LicenseInfo: MIT
      RetentionPolicy: Retain
Outputs:
  YoutubeToSpotifyHelperLayerARN:
    Value:
      Ref: YoutubeToSpotifyHelperLayer
    Description: YoutubeToSpotifyHelperLayer ARN
    Export:
      Name: youtube-to-spotify-helper-layer-arn
