version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "YoutubeToSpotify"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1qhprxmwx1dd5"
s3_prefix = "YoutubeToSpotify"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"

