AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: SAM Template for Youtube to Spotify Application

Resources:

    YoutubeToSpotifyFunction:
        Type: AWS::Serverless::Function
        Properties:
            FunctionName: YoutubeToSpotify
            Description: Youtube to Spotify main function
            Role: arn:aws:iam::079866621733:role/YoutubeToSpotify
            CodeUri: src/
            Handler: main.handler
            Runtime: python3.7
            Timeout: 900
            Environment:
                Variables:
                    ENV: production
            Layers:
                - !Ref YoutubeToSpotifyHelperLayer

    YoutubeToSpotifyHelperLayer:
        Type: AWS::Serverless::LayerVersion
        Properties:
            LayerName: YoutubeToSpotifyHelperLayer
            Description: Helper layer for Youtube to Spotify
            ContentUri: layers/youtube-to-spotify-helper-layer/function.zip
            CompatibleRuntimes:
                - python3.7
            LicenseInfo: MIT
            RetentionPolicy: Retain

Outputs:
    YoutubeToSpotifyHelperLayerARN:
        Value: !Ref YoutubeToSpotifyHelperLayer
        Description: YoutubeToSpotifyHelperLayer ARN
        Export:
            Name: youtube-to-spotify-helper-layer-arn